name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: yarn init
        run: |
          npm install yarn -g
          yarn install

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1
        with:
          skip-upload: true
          skip-deploy: true
          skip-release: true
          skip-readme: true
          bundle-command: yarn bundle
          # store-endpoint: ${{ secrets.STORE_ENDPOINT }}
          # store-access-token: ${{ secrets.STORE_ACCESS_TOKEN }}
          # server-endpoint: ${{ secrets.SERVER_ENDPOINT }}
          # server-access-key: ${{ secrets.SERVER_ACCESS_KEY }}
          # server-access-secret: ${{ secrets.SERVER_ACCESS_SECRET }}
          # slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          # github-token: ${{ secrets.GITHUB_TOKEN }}
